# Generated by Django 4.0.4 on 2022-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='no author', max_length=50),
        ),
    ]
