# Generated by Django 4.0.4 on 2022-05-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0006_remove_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo_url',
            field=models.CharField(default='no summary', max_length=250),
        ),
    ]
